[tool.poetry]
name = "aws"
version = "0.1.0"
description = ""
authors = ["FilipLysak001"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
